### PR TITLE
fix: ignore venv directory and non poetry pyproject.toml files (#14)

### PR DESCRIPTION
**Pull request by Toilal**

### CODE REVIEW

**Review by ajkerrigan — APPROVED** [review]
good call, thanks :+1:

**Review by ajkerrigan — COMMENTED** [review]
Actually hang on, I think the point about watching out for .venv is a good one but noticed that there are now two project_root methods which feels likely to cause confusion. Thanks nonetheless, just needs another look :sweat_smile:

**Comment by Toilal** [comment]
> now two project_root methods which feels likely to cause confusion

Hi, the `project_roots` function has been extracted for it to be unitary tested. I'll fix the PR for linter to be happy.

**Comment by Toilal** [comment]
@ajkerrigan @kapilt i've just rebased this PR, could you have a look and tell if I need to change anything ?

**Comment by georgealexanderday** [comment]
Hi there, is there any movement on this? Would be great to get in

**Comment by Toilal** [comment]
@ajkerrigan @kapilt please can we merge this ? and perform a release after ?

**Review by ajkerrigan — COMMENTED** [review]
Sure, don't have access to your repo so will get coverage sorted separately.

**Pull request merged**
